### ISSUE TITLE
A pure Rust full SSH client equivalent

### ISSUE THREAD

**Issue by aravindhsampath** [ErichDonGubler/not-yet-awesome-rust#12]
A pure Rust full SSH client equivalent to [Go's implementation](https://godoc.org/golang.org/x/crypto/ssh)

I wanted to use Rust for writing an application that can send commands to a fleet of servers over SSH. But, it doesn't look like there is an official pure Rust solution. I understand there are ssh2-rs (wrapper over libssh2 written in C) and Thrussh(not a feature complete client equivalent to that of Go SSH). It would be awesome to have an official Rust SSH library.

**Comment by ErichDonGubler** [comment]
I would love to add this to the list! Before I add it, I'd like to figure out what exactly something like Thrussh is missing -- that way, maybe somebody can hack on it, or understand what the differences are straight away. Do you know what they are? If not, could you research that and list it here? :)

**Comment by ErichDonGubler** [comment]
Unless I can elicit a list of what's incomplete about Thrussh, this issue doesn't seem very actionable. I'm planning on closing this issue unless there's further feedback this coming Tuesday.

**Comment by ErichDonGubler** [comment]
No more discussion has happened here, so...closing!
