### ISSUE TITLE
XML technology stack

### ISSUE THREAD

**Issue by crlf0710** [ErichDonGubler/not-yet-awesome-rust#13]
Some crates in this field do exist, however not in production ready state.
* General purpose DOM tree.
* Proper ncoding handling.
* DTD handling.
* XML Schema validation.
* XPath
* XQuery
* XSLT

**Comment by ErichDonGubler** [comment]
/u/StyMarr gave [at least one use case](https://www.reddit.com/r/rust/comments/7p1s2l/notyetawesome_rust_tell_us_the_use_cases_you/dsf497i/) in a reply to our first post to Reddit:

> On the feature side, I'm thinking about DTD and XPath especially. Also, being fast would be nice. I've been using xml-rs last year, and it was sloooooooooooooooooow.
> 
> My dream XML library for Rust would be something akin to Diesel, which gives you a statically-typed view of your XML Document, inferred from the DTD with some kind of infer_schema! macro. But I don't even know if it's possible (it should be possible since Rust type system is Turing Complete, but I don't know if it's doable in a convenient way in practice).

The features list is a subset of what you've listed here, but the use case for something like the `infer_schema!` macro that was discussed actually seemed really interesting.
