### ISSUE TITLE
GUI crate (Part 1: using native controls)

### ISSUE THREAD

**Issue by crlf0710** [ErichDonGubler/not-yet-awesome-rust#14]
A uniform abstraction and API above native controls solution on each platform.
There are some crates, just not awesome yet.

**Comment by ErichDonGubler** [comment]
>There are some crates, just not awesome yet.

What's missing? Could we get a list of things going that the current libraries lack? :)

**Comment by antoyo** [comment]
If we take the example of my crate [`relm`](https://github.com/antoyo/relm), you only get native controls on Linux and the API is not stable yet.
Also, more widgets could benefit from the declarative syntax.

**Comment by ErichDonGubler** [comment]
@antoyo: If I understand you:
* Some/many GTK preset widgets aren't supported yet? Or is it just that you can't use the declarative syntax from `relm`? 
* Support for other OSes is lacking in `relm`, or is it just that the styling doesn't look native on something like Windows?

**Comment by antoyo** [comment]
@ErichDonGubler:

 * Yeah, for instance, one [cannot use Menu](https://github.com/antoyo/relm/issues/54) with the declarative syntax, even tough it's possible to mix the declarative syntax with the imperative syntax of `gtk-rs` in `relm`.
 * The look isn't native and `gtk` is not considered as a good option on Windows and Mac by some people. Also, some futures related stuff is not working for Windows in relm.

**Comment by ssokolow** [comment]
For the record, I consider the direction GNOME 3 has been pushing GTK+'s built-in widgetry to be alien enough on a KDE desktop that I don't think you can say "native controls on Linux" any more than you can lump Linux and OSX together as both being POSIX-based OSes with X11 API support.

(I either write my GUIs in PyQt or, if the backend code has an identity separate enough from the UI to be feasibly encapsulated, I consider using `rust-cpython` to move it into Rust.)

**Comment by zmitchell** [comment]
I'm currently working on rewriting the parser for `relm`'s declarative layout macro, which should speed up implementation of new features. That being said, I don't think GTK+ will/should become 🙌 The Chosen One 🙌 because it definitely doesn't look native on Mac, and I suspect it doesn't really look native elsewhere either.

I think the standout feature of `relm` is its declarative layout macro and the whole message passing system. It makes it really easy to hook up all the layout, events, etc. The macro system is a huge boon here since you have a blank slate to start from when deciding how you want the syntax to look, so I think whatever solution ends up coming out on top should take advantage of that.

**Comment by crlf0710** [comment]
For windows usages, a crate called `native-windows-gui` seems to make the most progress atm. Would really love to see something cross platform and awesome, though!

**Comment by ErichDonGubler** [comment]
So, I'm thinking that this issue could be broken out into several use cases from the discussion given so far:

* Native UIs for each major platform that Rust supports:
    * Windows
        * [`native-windows-gui`](https://crates.io/crates/native-windows-gui) seems to be the current state of the ecosystem, which is in beta and still waiting on some important features before stability.
    * Mac
        * The Servo team actually maintains the [`cocoa` crate](https://github.com/servo/cocoa-rs), so this seems satisfied already.
    * Linux HAS no canonical UI toolkit, and what with `gtk-rs` and the `qt` crate seeming fairly mature, so this is probably already satisfied.
* A unified API for native controls (per the OP of this issue) seems not to exist yet. It sounds...actually really hard. :) ***There are still no suggested deficient crates here, and I don't see any that seem to fit this criteria.***

**Comment by ErichDonGubler** [comment]
Created a PR request here, in hopes that we've captured everything so far: https://github.com/ErichDonGubler/not-yet-awesome-rust/pull/29

Feel free to leave feedback!

**Comment by antoyo** [comment]
> Native UIs for each major platform that Rust supports:
Isn't `wxWidgets` the solutions to that. Would having a `wxWidgets` Rust port be sufficient?

**Comment by ErichDonGubler** [comment]
@antoyo: wxWidgets (and something like a pure-Rust [wxRust](https://github.com/kenz-gelsoft/wxRust)) seems like it'd be sufficient, if a massive effort. :)

**Comment by ssokolow** [comment]
Last I checked, wxWidgets had no Qt backend and the API wxPython exposed for it was inferior to both PyGTK and PyQt for comfort.

I've been using wxPython recently for a little utility and it still exposes an API that reminds me more of raw Win32 than of the APIs exposed by GObject Introspection or Qt. (eg. Raw numeric IDs where you have to root around for why you might want to specify something other than `-1`, `flags` bitfields which lump all sorts of different meanings into the same variable with little or no compile-time checking for which flags make sense on which widgets, etc.)

**Comment by ErichDonGubler** [comment]
I'm announcing an "FCP" of sorts on here, seeing as I haven't gotten any feedback on PR #29 yet. I'm hoping to close it by the end of the week -- even if you feel like you don't have much substance behind a comment you're thinking of, feel free to throw it out there!

**Comment by ErichDonGubler** [comment]
To make things clear, I'm also hoping to close this issue at the end of this week, too, so don't wait! The discussion here has been great -- thank you so much for contributing!

**Comment by ErichDonGubler** [comment]
No comments, so I'm closing this. Thanks, everyone!
