### ISSUE TITLE
GUI crate (Part3: Using web technology)

### ISSUE THREAD

**Issue by crlf0710** [ErichDonGubler/not-yet-awesome-rust#15]
Production ready GUI using web technology, with support for HTML dialog etc.

Seems libservo is the way to go?

**Comment by ErichDonGubler** [comment]
I'm not sure; I heard of [`webrender`](https://github.com/servo/webrender) being discussed as a potential way to render HTML UIs, but it seems some people are using `libservo` at least as proofs of concept, like [`servo-embedding-example`](https://github.com/paulrouget/servo-embedding-example).

I honestly wouldn't mind inlining what you've written into the list, but I'm curious what other features would be necessary at this point in your writing (emphasis mine):

> Production ready GUI using web technology, with support for HTML dialog ***etc.***

What is "etc."? I'm not familiar with this, and I'm sure a more elaborate list of features would only help a hopeful implementer. :)

**Comment by crlf0710** [comment]
I'm not very familiar with web-based GUI technologies too. I'll point to `electron`, `cordova` and `react-native` as examples of what people might be expecting, but sure, they might be an overkill.

**Comment by ErichDonGubler** [comment]
I'm not sure that this use case isn't actually fulfilled yet -- between `webrender`, `servo`, and the new [`web-view`](https://crates.io/crates/web-view) crate, it seems like people are trying to fill this need already.

I'm planning on closing this issue by this coming Tuesday unless more feedback is received here. Thanks for the great issues @crlf0710!

**Comment by ErichDonGubler** [comment]
No more discussion has happened here, so...closing!
