### ISSUE TITLE
Registry.pol parser thingy implemented

### ISSUE THREAD

**Issue by nabijaczleweli** [ErichDonGubler/not-yet-awesome-rust#16]
I found this, looked at the format spec, and [implemented it](https://crates.io/crates/registry-pol).

**Comment by ErichDonGubler** [comment]
This is awesome! Gave the crate some feedback -- I think I'd like to test it and get involved myself, since I've actually been working on something like this too, but here we can cross out that item in the list now!

You rock! :)
