### ISSUE TITLE
QR reading library?

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/not-yet-awesome-rust#17]
[This comment](https://www.reddit.com/r/rust/comments/7p1s2l/notyetawesome_rust_tell_us_the_use_cases_you/dse12wm/) on the introductory Reddit post indicates there's a lack of QR **reading** libraries. In my own searching, I've found plenty of libraries to WRITE QR codes, but READING this seems to be a legitimate hole in the ecosystem.

However, I'm not sure what this exactly would entail, or even the original use case of this user. It seems that there's a QR **decoder** in [this crate](https://crates.io/crates/quirc); it's the only crate that speaks of decoding that I can see, and it has a C dependency, so there may not be a pure-Rust QR decoding implementation either. I understand that a computer vision library would be required to read a QR code from an image in order to extract QR code to decode in the first place. Perhaps that's all there is?

I'll wait for somebody who knows more than I do to confirm this.

**Comment by ErichDonGubler** [comment]
@nabijaczleweli: As somebody with literally no authority in the Rust ecosystem...so long as a quality crate is out there, I don't see why not! :) Now, here're my concerns with RIIR'ing that chunk of C code:

* There's no tests on that C code, so I don't even know if it works correctly in the first place. Some verifiable tests of actual QR data samples would be the most powerful testament to whether it does or not.

    At the very least, I suppose you can at least compare data sample output with this library's. That would be good with establishing that a new crate would have at least equal functionality, independent of whether or not that behavior is actually correct.
* I hope by "translating" you mean iterating over getting the code working, and THEN making it idiomatic Rust...because making it idiomatic and nice to maintain would be sweet!

**Comment by nabijaczleweli** [comment]
I'll get on doing a translation in the near future, then. (I usually use transliteration as getting code in lang B to work like code in lang A and translation as making it idiomatic/usable/etc.)

**Comment by ErichDonGubler** [comment]
I think it's fairly safe to say that there seems to be a lack of interest in further defining use cases for this domain, so I'll use [the most recent commit](https://github.com/ErichDonGubler/not-yet-awesome-rust/commit/693d0bacf5ddd863fc481fc9851c21981ef7aea0) to close this issue.
