### ISSUE TITLE
"Inheritance, or some inheritance-like construct"?

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/not-yet-awesome-rust#18]
Originally requested on Reddit [here](https://www.reddit.com/r/rust/comments/7p1s2l/notyetawesome_rust_tell_us_the_use_cases_you/dsf7dnw/?context=3).

I think I can see several use cases for this with UI work specifically, though there are alternative techniques used in C and some Rust libraries already. For example, I know that [GTK-rs](https://coaxion.net/blog/2017/09/exporting-a-gobject-c-api-from-rust-code-and-using-it-from-c-python-javascript-and-others/#objects) uses the functionalities that the `glib` library already provides for manually constructing what amounts to a vtable.

**Comment by torpak** [comment]
You might try composition instead. It usually leads to cleaner and more understandable code.
GTK tries to emulate old style c++ like OOP in c.
You can do something similar in rust but please don't try to get OOP into the language.
IMHO OOP is useful only in very few cases, but overused everywhere it is available.
[Look here for a more detailed view](http://harmful.cat-v.org/software/OO_programming/why_oo_sucks)

**Comment by ErichDonGubler** [comment]
You might get a chuckle to hear that the OP also wrote this to preempt the kind of response you just gave (censorship mine):

> And please don't be the condescending **** that tells me I don't need inheritance, or some platitude like composition over inheritance. I've been doing functional programming my entire career. I'm well aware of how it's done, as well as its relative strengths and weaknesses. *And for some applications, inheritance is absolutely the better abstraction.*

So far, all I've heard is a debate between the concept of composition vs. inheritance. I am planning on closing this issue unless somebody comes forward with a solid use case. The OP has not provided one, and without one this is not actionable for the Rust community.
