### ISSUE TITLE
"fully-featured" concurrent maps?

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/not-yet-awesome-rust#19]
Inlined from [this Reddit reply](https://www.reddit.com/r/rust/comments/7p1s2l/notyetawesome_rust_tell_us_the_use_cases_you/dsetf3a/) on the introductory /r/rust thread:

> I couldn't find any fully-featured concurrent maps. They all seem to have some missing parts, like lookup given a borrowed key.

**Comment by ErichDonGubler** [comment]
So, I know that *I* don't know anything about what "fully-featured" means here...could we elaborate more of the "missing parts" that have been mentioned? Why are the current libraries like [`rust-concurrent-hashmap`](https://github.com/veddan/rust-concurrent-hashmap) and [`rust-evmap`](https://github.com/jonhoo/rust-evmap) insufficient?

**Comment by stjepang** [comment]
I think "fully-featured" would mean that you can easily replace any use of `Mutex<HashMap<K, V>>` with something like `ConcurrentHashMap<K, V>` and expect the code to just work, without too many additional obstacles or caveats.

`rust-concurrent-hashmap` looks decent, but is still missing methods like `iter_mut`, `entry`, `drain`, and `clear`. Struct `MutAccessor` is not public, which seems like an oversight, indicating that the crate still needs some polish.

`rust-evmap` is a rather special hash table. It allows a single writer only, and offers eventual consistency only. The interface departs from that of `HashMap`.

Take Java's collections for example. You can literally just replace `HashMap<K, V> map = new HashMap<>()` with `HashMap<K, V> map = new ConcurrentHashMap<>()` and have a map that works without synchronization. There is no need to adapt the code to a different interface, you don't have care about eventual consistency vs sequential consistency, and you can have as many writers and as many readers as you wish. The switch from `HashMap` to `ConcurrentHashMap` is totally painless and comes with very few caveats.

While `rust-evmap` and `rust-concurrent-hashmap` attempt to mimic `HashMap`, I'm working on a concurrent map that attepts to mimic `BTreeMap`. Take a look at the [RFC](https://github.com/crossbeam-rs/rfcs/pull/27) proposing to include it into Crossbeam. Feedback would be very welcome! :)

**Comment by ErichDonGubler** [comment]
@stjepang: I've made a PR [here](https://github.com/ErichDonGubler/not-yet-awesome-rust/pull/33) to try to encapsulate this discussion. How's it look?

**Comment by ErichDonGubler** [comment]
I'm planning on closing this issue by Friday if no further discussion happens by then. Thanks for the contribution, everyone!

**Comment by stjepang** [comment]
Looks good to me!

**Comment by ErichDonGubler** [comment]
No further discussion, so closing this -- thanks, @stjepang! :)
