### ISSUE TITLE
Dynamic program analysis domain?

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/not-yet-awesome-rust#20]
Basically, there's not much in this domain right now. But what can we tell others to give them a good reference of what feature set to implement?

See [this Reddit reply](https://www.reddit.com/r/rust/comments/7p1s2l/notyetawesome_rust_tell_us_the_use_cases_you/dsesbse/) to the introductory post for /r/rust:

> Definitely an instrumental tool like Intel Pin or DynamoRIO. My big dream...

**Comment by ErichDonGubler** [comment]
I will be adding only a very basic entry, unless somebody has more input to give by this coming Tuesday.

**Comment by ErichDonGubler** [comment]
I've received no feedback for this issue, but I'll leave the PR open for a bit. See it here: https://github.com/ErichDonGubler/not-yet-awesome-rust/pulls

**Comment by cento** [comment]
Hi, I'm the commenter on Reddit. As I said, I'd like to have an instrumental tool written in Rust because of the large usage in academia/industry for simulators, debugging and reverse engineer. 
Which kind of details do you need, @ErichDonGubler ?
Anyway, thanks for opening the issue, at least we can start to talk about that.

**Comment by ErichDonGubler** [comment]
@cento: The first thing you can do (and I hope we can start discussion about more) is take a look at the PR I linked above and tell me if I'm missing any details you'd like in the list and what those are.

I'm most interested in finding use cases to list, and you've already given a few here... So maybe I should just update the PR? :)

**Comment by cento** [comment]
Hi @ErichDonGubler , basically instrumental tools usually provide information for understanding and tuning the execution behaviour of apps. They are used during the app development, but also for memory/flow debug, in reverse engineering, and in the HPC simulation field. 

Using the right instrumental tool, you can verify performance bottleneck, enforce a modification to the application flow, and most important (at least in HPC), you can intercept instructions and system calls generating a trace of dynamic executed instructions. This last use is important (fundamental?) for trace-drive simulations.

Having a pure-rust instrumental tool library could help to break the C++-dependency of a lot of important tools (and research groups) from these libraries. 
IMO this is one of the most important missing opportunity in the Rust library ecosystem.

I hope these info are enough for your pull request.

**Comment by ErichDonGubler** [comment]
@cento: Gah! Sorry, I've been lost in the mass of feedback I've received from my recent reposting of NYAR on Reddit -- this got lost in the noise for a bit.

I think that the information you've given here is fantastic, and just what I need. Thanks for getting it to me. :) I'll do my best to summarize what you've got here, and update the PR -- I'll let you know when I've updated it and would like your "LGTM". :)
