### ISSUE TITLE
Some more exotic ideas...

### ISSUE THREAD

**Issue by sauer2** [ErichDonGubler/not-yet-awesome-rust#22]
Full disclosure: I'm not even a Rust user right now, so I kind of am an idea guy here. If you feel this issue is a waste of your time, don't resist deleting it. ;)

- Since an XML parser is already listed, I give you... SGML. I know it's basically dead and you won't find one to write a parser, but to my knowledge at least some publishers still used this format about ~5 years ago, maybe they still do. Most likely you'd do legacy support. [The one repo I found seems to be dead.](https://github.com/tylersouthwick/rust-sgml)
- for the XML wish list: XSLT 2.0 support, options to control XML whitespace behavior (like for preserving whitespace), options to disable all XML footguns like entity bombs
- a library that helps implementing GUI libraries (offers OS callback based event handling, unlike SDL2 or SFML, offers drawing primitives, text, images, so you don't have to mess around with OpenGL, Vulkan or other low level backends, helps with different ppi numbers?)
- parser/operations API/renderer for PCRaster maps (category GIS or spatial modelling)
- likewise a parser for Rdata files (statistics/modelling)?

**Comment by sauer2** [comment]
As it turns out, XSLT is already at version 3.0.

**Comment by ErichDonGubler** [comment]
I've seen this comment, and I hope I'll get to responding to it shortly. Thanks for taking the time to file an issue! :)

**Comment by ErichDonGubler** [comment]
Sorry for taking so long to follow up here! Let me see if I can extract some uses cases from what you've got here...

I'll put stuff from this issue into [this PR](https://github.com/ErichDonGubler/not-yet-awesome-rust/pull/36). Let's take this conversation there, yeah?

**Comment by ErichDonGubler** [comment]
I'm going to close this issue, since lots of feedback is happening on the PR. 

Thanks for taking the time to open it! 😄
