### ISSUE TITLE
Reading and writing of Office file formats

### ISSUE THREAD

**Issue by silwol** [ErichDonGubler/not-yet-awesome-rust#25]
A use case that I frequently stumble upon is to import and export Office files. It would be fine to have one or several good libs to read and write OfficeOpenXML (Excel, Word…) as well as OpenDocument (Sheets, Writer…) files. A bonus would be to have the same representation for the different formats of the same document type (Excel and Sheets), so it could easily be used to import and export the same data structure from/to either format, as well as perform conversions between them.

**Comment by ErichDonGubler** [comment]
So, I'm seeing several use cases here, and I'm hoping to elaborate more detail for each:

* Import/export common office document formats, with some way to interact with their contents.
    * Excel/Calc spreadsheet deserialization seems available with [`calamine`](https://crates.io/crates/calamine), but [no serialization libraries seem available](https://crates.io/search?q=office) for them, let alone for the entire XML formats that the Office/OpenOffice suites themselves support.
* Have a way to convert between different word processing formats would also be nice.
* Also, from what I remember with my brief experience building some Excel sheet manipulation with Python, one can actually interact with the same APIs that Visual Basic uses for scripting by using the COM interface, which I believe [`winapi`](https://crates.io/crates/winapi) supports.

Am I missing anything?

**Comment by crlf0710** [comment]
From the implementation aspect, this is largely based on the XML thing... Also, the Word format needs to deal with very large XML files, so special handling needs to be involved.

**Comment by mmstick** [comment]
The problem with OOXML is that not even Microsoft follows and implements their own specification properly. The OpenDocument formats, on the other hand, are much more realistic.

**Comment by crlf0710** [comment]
@mmstick It's not that bad. I've implementation something (in C++ though) for work before. MSOffice implements the "transitional" flavor of OOXML (which is defined in part 4) in 2007 and 2010 (2007 support is really incomplete, do not use it), and use it as default. The "strict" flavor's reading and writing support  (which is defined in part 1) is gradually added in later versions of MSOffice and not set as default.

**Comment by ErichDonGubler** [comment]
I'm finalizing the output of this discussion with [this PR](https://github.com/ErichDonGubler/not-yet-awesome-rust/pull/32) -- I'll be closing this by Tuesday, unless somebody has something that needs to be discussed further.

Thank you for your contributions so far, everyone!

**Comment by ErichDonGubler** [comment]
No more discussion has happened here, so...closing!
