### ISSUE TITLE
ReactiveX / Rx / FRP

### ISSUE THREAD

**Issue by polarathene** [ErichDonGubler/not-yet-awesome-rust#6]
Rx(Reactive Extensions) is quite popular library available in many different languages, [there have been attempts in the past](https://github.com/ruuda/rx) to port to Rust but they've not quite taken off(either not enough interest, contributors or language barriers such as async not being well supported at the time).

[RxRust](https://github.com/ReactiveX/RxRust/issues/7) issue suggests that things can be better now with tokio and futures support, as well as futures stream module?(streaming iterators being a desirable feature I and others have been looking forward to in Rust where regular iterators are not appropriate)

[Carboxyl](https://github.com/aepsil0n/carboxyl/issues/107), which seems like a good crate trying to offer this points out that Rust lacks decent support for creating declaritive UI components that'd benefit the most(ala React/React-Native equivalent). They later discuss some crates that are offering declaritive UI and that the Async story is better now but their crate would likely need a re-write.

You also have something similar, known in Clojure as Transducers, two Rust crates try to offer this: https://github.com/ruuda/transducers
https://github.com/benashford/rs-transducers

Both haven't been touched since May 23 2016, I haven't personally tried them but assume they're out of date or could be improved on(rs-transducers mentions some limitations they had at the end of their readme). The first repo links to [this youtube video](https://www.youtube.com/watch?v=6mTbuzafcII) to explain Transducers. They seem quite similar to chaining methods with an iterator, you can compose a series of methods as the video shows making good use of reusability. 

I recall working on a project in the past where I wanted to compose some functions together but couldn't do it well with Rust and my knowledge at the time. The above would possibly have helped on the project, or streaming iterators(large amount of computation and data with unknown length/completion time that would process chunks of data), trying to support composable function variants based on settings/parameters was difficult to figure out(I think due to lifetimes or other compiler issues with typing/inference). Impl Trait and some other features on their way would help with my issue and perhaps help improve these crates to provide a solid offering in Rust for those looking for Rust equivalent.

**Comment by ErichDonGubler** [comment]
I think that FRP is valuable, and one of the biggest issues I've noticed newcomers have to understanding the value of a "pure" data transformation pipeline is showing specific use cases where it would be beneficial. I'm trying to see how I can make these suggestions concrete enough that somebody looking at the repo's main list would be able to act. Here's some ideas -- what do you think of them?

- We can mention that **a good stream processing pipeline with back pressure doesn't yet exist for some use cases or library qualities** (and those use cases and/or rough edges should be mentioned with examples!).
    - The Reactive Streams site has an interesting [problem statement](http://www.reactive-streams.org/#the-problem):

        > Handling streams of data—especially “live” data whose volume is not predetermined—requires special care in an asynchronous system. The most prominent issue is that resource consumption needs to be controlled such that a fast data source does not overwhelm the stream destination. Asynchrony is needed in order to enable the parallel use of computing resources, on collaborating network hosts or multiple CPU cores within a single machine.

        The use case here seems to be creating an [observer-subject](https://en.wikipedia.org/wiki/Observer_pattern) relationship on an async boundary and providing mechanisms of back pressure to avoid resource exhaustion.

- We can also mention that attempts have been made in the past, but that new developments like `impl Trait` will probably make developing an reactive streams library easier to both develop and use.

**Comment by aepsil0n** [comment]
Author of [carboxyl](https://github.com/aepsil0n/carboxyl) here. Nice to see people thinking about this topic again. I sort of lost track of the FRP topic a while ago, but I am happy to provide input on the issue, as I spent quite a bit of time figuring this out.

**Comment by ErichDonGubler** [comment]
@aepsil0n: It would be wonderful to hear your responses to what's already been discussed and to hear whatever else you have to add. I'm just looking for actionable use cases!

**Comment by polarathene** [comment]
Watching the video on transducers would give a good idea of where it's beneficial? I don't personally have much experience with using this approach to programming myself but I have had interested in trying it some day.

I remember when I last looked into the subject it was showing lines with different shapes/colours and how to process/transform them(on the different lines) by filtering/matching conditions/types of data. There was a really nice JS talk on youtube somewhere that gave many good examples of how to approach scenario's differently, and how they became easier or less complicated by using event streams instead of traditional non-functional approach. I think one of the examples was to do with mouse click events, detecting double clicks, debouncing, etc. 

Another perk was composability iirc, transducers video talk explains that type of development really well, I'm not sure how well it carries over to Rust. I know with Rust you can chain methods with iterators, but I also remember having a desire to split that chain into 3-5 stages that could be composed differently depending on data/settings. I don't recall having success with that, and some other attempts didn't work well due to how closures work in Rust. It could just be that Rust needs to gain some of the current features in development first before this is a smoother experience.

**Comment by ErichDonGubler** [comment]
It seems that the two major use cases for FRP are:

* As a framework to create an asynchronous data processing pipeline
* As a framework for user interfaces, sometimes with a state management solution that facilitates a [Flux architecture](https://facebook.github.io/flux/)

I've tried capturing what I've taken away from this discussion [here](https://github.com/ErichDonGubler/not-yet-awesome-rust/pull/35), and am declaring a final comment period on this issue. Please give your input -- I definitely want these entries to be complete for the use cases put forth! :)

**Comment by ErichDonGubler** [comment]
Closing, since I've seen no feedback yet and it's Friday 🎉 . Feel free to still comment here or to open another issue if you need to holler!
