### ISSUE TITLE
(Official like) Google Client Libraries

### ISSUE THREAD

**Issue by csharad** [ErichDonGubler/not-yet-awesome-rust#7]
The Google client libraries are used in Google Cloud Platform to manage resources.

Rust has a library which solves this particular use case [`google-apis-rs`](https://github.com/Byron/google-apis-rs) but it is not beginner friendly to use. It is autogenerated using Google Discovery Service. 

And the new & official way to create user-friendly APIs is to use [`googleapis`](https://github.com/googleapis/googleapis) to autogenerate. It uses [grpc](https://grpc.io/) which has Rust implementations at [1](https://github.com/stepancheg/grpc-rust) & [2](https://github.com/pingcap/grpc-rs) though they are still under development and would require much effort to bring it to feature parity to the official one. (Also a complete grpc would benefit micro-services server-client architecture.)

I would help because I require this but I don't know how it works and I am a beginner at Rust. It is needed, to use Google cloud storage for my Rocket app.

**Comment by ErichDonGubler** [comment]
So, let's see if I understand what your missing use case:

> `google-apis-rs`....is not beginner friendly

So, it's hard to discover how to actually use this...yeah, I've tried to decipher how to use stuff like the GMail API from these crates. I wasn't able to do so either. I think this is mostly a documentation problem -- if somebody could write docs that actually helped us understand these libraries, then we might actually be able to use them. Sound like your experience?

**Comment by csharad** [comment]
Yes, that is the case. To use the API, we need to import `yup-oauth2`, `hyper` and do some juggling between the three to make it work.

If the API would have only one entry to make it all work much like the official one, then that would be awesome.

**Comment by ErichDonGubler** [comment]
> If the API would have only one entry to make it all work much like the official one, then that would be awesome.

Which official one is that? I'm not too famiilar with the Google API docs, actually...

**Comment by csharad** [comment]
Also much like Google's official ones, an alternate API could be generated using `grpc` as I have stated above. Those would be faster than the REST-based `google-api-rs`.

**Comment by csharad** [comment]
I meant if it had the following API surface.
[Python Client](https://pypi.org/project/google-cloud-storage/)

**Comment by ErichDonGubler** [comment]
@csharad: How does [this commit](https://github.com/ErichDonGubler/not-yet-awesome-rust/commit/175d11593fde8d616d8b55c3e2d371408147c635) look for my understanding of the problems you're trying to solve? Do they sound right?
